# Generated by Django 4.1.7 on 2023-03-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminusers2',
        ),
        migrations.AddField(
            model_name='adminusers',
            name='role',
            field=models.CharField(default='admin', max_length=10),
        ),
        migrations.AddField(
            model_name='faculties',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=50),
        ),
        migrations.AddField(
            model_name='students',
            name='admission_id',
            field=models.CharField(default='m001', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_code',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
